/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'NoxUmbrarum' at '09.05.17 02:56' with Gradle 2.14.1
 *
 * @author NoxUmbrarum, @date 09.05.17 02:56
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
